DROP TABLE IF EXISTS undone_tasks;

CREATE TABLE undone_tasks (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    time DATE NOT NULL DEFAULT CURRENT_DATE,
    title TEXT NOT NULL,
    is_frog BIT NOT NULL
);

DROP TABLE IF EXISTS done_tasks;

CREATE TABLE done_tasks (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    time DATE NOT NULL DEFAULT CURRENT_DATE,
    title TEXT NOT NULL,
    is_frog BIT NOT NULL
);
